import test from 'node:test';
import assert from 'node:assert/strict';
import { calculate } from '../src/apps/calculator.js';
import { winnerFor } from '../src/apps/rps.js';
import { floodFill, randomColor } from '../src/apps/ganvas.js';
import { roomPhase } from '../src/apps/room.js';
import { createPrismLevel, traceBeam } from '../src/apps/prism.js';
import { CAFE_RECIPES, orderPoints, recipeMatches } from '../src/apps/cafe.js';
import { bestTicTacToeMove, createMemoryDeck, guessHint, winningLine } from '../src/apps/classics.js';
import { fruitReward, nextHead, oppositeDirection, snakeCollision } from '../src/apps/snake.js';
import { laneHit } from '../src/apps/night.js';
import { canWalk, parcelDistance, PARCEL_MAP } from '../src/apps/parcel.js';
import { platformLanding } from '../src/apps/patchwork.js';
import { flightStep, ringCollected } from '../src/apps/skies.js';

test('calculator operations and zero division', () => { assert.equal(calculate('8', '÷', '2'), 4); assert.equal(calculate('1', '÷', '0'), 'Not a number'); });
test('hand game outcomes', () => { assert.equal(winnerFor('rock', 'scissors'), 'player'); assert.equal(winnerFor('rock', 'paper'), 'computer'); assert.equal(winnerFor('rock', 'rock'), 'draw'); });
test('flood fill stays within connected region', () => { assert.deepEqual(floodFill(['w','w','x','x'], 2, 0, 'r'), ['r','r','x','x']); });
test('rainbow brush produces a valid rgb colour', () => { assert.match(randomColor(), /^rgb\(\d{1,3}, \d{1,3}, \d{1,3}\)$/); });
test('room phases cover the day', () => { assert.equal(roomPhase(5), 'night'); assert.equal(roomPhase(7), 'dawn'); assert.equal(roomPhase(12), 'day'); assert.equal(roomPhase(18), 'dusk'); });
test('prism levels solve at their intended rotations', () => { for (let index = 0; index < 3; index++) { const level = createPrismLevel(index); const solved = level.tiles.map(tile => tile.path ? { ...tile, rotation: tile.correct } : tile); assert.equal(traceBeam(solved, level.size).success, true); } });
test('prism levels begin unsolved', () => { assert.equal(traceBeam(createPrismLevel(0).tiles, 5).success, false); });
test('cafe recipes match in any ingredient order', () => { assert.equal(recipeMatches(['foam','coffee','milk'], CAFE_RECIPES[0]), true); assert.equal(recipeMatches(['foam','berry','milk'], CAFE_RECIPES[0]), false); });
test('cafe combo rewards increase points', () => { assert.ok(orderPoints(80, 3) > orderPoints(80, 1)); });
test('tic-tac-toe detects wins and blocks immediate losses', () => { assert.deepEqual(winningLine(['X','X','X','','','','','','']), [0,1,2]); assert.equal(bestTicTacToeMove(['X','X','','O','','','','','O']), 2); });
test('tic-tac-toe takes an immediate winning move', () => { assert.equal(bestTicTacToeMove(['O','O','','X','X','','','','']), 2); });
test('memory decks contain exactly two of every symbol', () => { const deck=createMemoryDeck(['A','B'],()=>.5); assert.equal(deck.length,4); assert.equal(deck.filter(card=>card.value==='A').length,2); });
test('number guess provides directional hints', () => { assert.equal(guessHint(20,40),'higher'); assert.equal(guessHint(60,40),'lower'); assert.equal(guessHint(40,40),'correct'); });
test('snake movement advances and can wrap', () => { assert.deepEqual(nextHead({x:4,y:2},{x:1,y:0},5,true),{x:0,y:2}); assert.deepEqual(nextHead({x:2,y:2},{x:0,y:-1},5),{x:2,y:1}); });
test('snake rejects direct reversals', () => { assert.equal(oppositeDirection({x:1,y:0},{x:-1,y:0}),true); assert.equal(oppositeDirection({x:1,y:0},{x:0,y:1}),false); });
test('snake collisions include walls, body, and hazards', () => { assert.equal(snakeCollision({x:-1,y:2},[],[],10),true); assert.equal(snakeCollision({x:2,y:2},[{x:2,y:2}],[],10),true); assert.equal(snakeCollision({x:3,y:3},[],[{x:3,y:3}],10),true); });
test('snake special fruit and combos reward more', () => { assert.ok(fruitReward('golden',2)>fruitReward('berry',1)); });
test('night defenders hit shadows only in their lane', () => { assert.equal(laneHit({lane:1,x:100},{lane:1,x:118}),true); assert.equal(laneHit({lane:1,x:100},{lane:2,x:100}),false); });
test('parcel routes reject hedges and measure delivery distance', () => { assert.equal(canWalk(PARCEL_MAP,0,0),false); assert.equal(canWalk(PARCEL_MAP,1,1),true); assert.equal(parcelDistance({x:1,y:2},{x:4,y:6}),7); });
test('platform landings require downward movement and overlap', () => { assert.equal(platformLanding({x:10,y:80,w:20,h:20,vy:4},{x:0,y:100,w:100,h:20},95),true); assert.equal(platformLanding({x:110,y:80,w:20,h:20,vy:4},{x:0,y:100,w:100,h:20},95),false); });
test('paper flight applies gravity and advances the course', () => { const next=flightStep({vy:0,y:100,distance:0,speed:100},0,1); assert.equal(next.vy,85); assert.equal(next.distance,100); });
test('paper planes collect only nearby stamp rings', () => { assert.equal(ringCollected({x:100,y:100},{x:210,y:100},100),true); assert.equal(ringCollected({x:100,y:100},{x:300,y:100},100),false); });
