export const NIGHT_DEFENDERS = {
  lamp: { name: 'Lamp', cost: 40, rate: 850, damage: 2, color: '#ffd166' },
  toy: { name: 'Toy Drum', cost: 55, rate: 550, damage: 1, color: '#e56f87' },
  book: { name: 'Storybook', cost: 70, rate: 1200, damage: 4, color: '#77b6a4' },
};
export const laneHit = (projectile, enemy) => projectile.lane === enemy.lane && Math.abs(projectile.x - enemy.x) < 24;

export function mountNight(root) {
  root.innerHTML=`<div class="feature-game night-game"><aside class="feature-copy"><p class="eyebrow">Survive until sunrise</p><h2>Night Shift</h2><p>The bedroom wakes after midnight. Place friendly objects in three dream lanes and keep the shadows away from the bed.</p><div class="feature-stats"><span>Dreamlight<b data-energy>120</b></span><span>Bed hearts<b data-hearts>5</b></span><span>Wave<b data-wave>1 / 5</b></span><span>Best<b data-best>0</b></span></div><div class="defender-shop">${Object.entries(NIGHT_DEFENDERS).map(([id,d])=>`<button data-defender="${id}" style="--defender:${d.color}"><i></i><b>${d.name}</b><small>${d.cost} light</small></button>`).join('')}</div><button class="feature-secondary" data-clear type="button">Remove selected object</button></aside><section class="feature-stage night-stage"><div class="night-hud"><b data-night-message>Select an object, then choose a rug square.</b><span data-countdown>Wave begins in 3</span></div><canvas width="800" height="540" aria-label="Three-lane bedroom defense board"></canvas><div class="feature-overlay"><p>Night Shift</p><strong>Can you reach sunrise?</strong><span>Five waves. Three lanes. One very sleepy bedroom.</span><button data-start>Begin the shift</button></div></section></div>`;
  const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'), energyEl=root.querySelector('[data-energy]'),heartsEl=root.querySelector('[data-hearts]'),waveEl=root.querySelector('[data-wave]'),message=root.querySelector('[data-night-message]'),countdown=root.querySelector('[data-countdown]'),overlay=root.querySelector('.feature-overlay');
  let selected='lamp', defenders=[],enemies=[],shots=[],energy=120,hearts=5,wave=1,best=Number(localStorage.getItem('playground:night-wave')||0),running=false,last=0,spawnAt=0,spawned=0,defeated=0,raf,waveDelay=3000;
  root.querySelector('[data-best]').textContent=best; root.querySelector('[data-defender=lamp]').classList.add('selected');
  function reset(){defenders=[];enemies=[];shots=[];energy=120;hearts=5;wave=1;spawned=defeated=0;waveDelay=3000;last=performance.now();spawnAt=last+waveDelay;update();draw();}
  function start(){reset();running=true;overlay.classList.add('hidden');message.textContent='Place your first defender.';raf=requestAnimationFrame(loop);}
  function waveSize(){return 4+wave*2;}
  function update(){energyEl.textContent=Math.floor(energy);heartsEl.textContent=hearts;waveEl.textContent=`${wave} / 5`;best=Math.max(best,wave);root.querySelector('[data-best]').textContent=best;localStorage.setItem('playground:night-wave',best);}
  function spawn(now){const tough=wave>=3&&Math.random()<.28;enemies.push({lane:Math.floor(Math.random()*3),x:760,hp:tough?8:4,speed:(tough?15:23)+wave*2,max:tough?8:4});spawned++;spawnAt=now+Math.max(650,1450-wave*130);}
  function loop(now){if(!running)return;const dt=Math.min(.04,(now-last)/1000);last=now;energy=Math.min(150,energy+dt*5);if(waveDelay>0){waveDelay-=dt*1000;countdown.textContent=`Wave begins in ${Math.max(1,Math.ceil(waveDelay/1000))}`;}else{countdown.textContent=`${defeated} / ${waveSize()} shadows tucked away`;if(spawned<waveSize()&&now>=spawnAt)spawn(now);}defenders.forEach(d=>{d.cool-=dt*1000;if(d.cool<=0&&enemies.some(e=>e.lane===d.lane&&e.x>d.x)){shots.push({lane:d.lane,x:d.x+25,damage:NIGHT_DEFENDERS[d.kind].damage,color:NIGHT_DEFENDERS[d.kind].color});d.cool=NIGHT_DEFENDERS[d.kind].rate;}});shots.forEach(s=>s.x+=dt*280);enemies.forEach(e=>e.x-=dt*e.speed);for(const s of shots){const target=enemies.find(e=>laneHit(s,e));if(target){target.hp-=s.damage;s.hit=true;if(target.hp<=0){target.dead=true;defeated++;energy=Math.min(150,energy+12);}}}shots=shots.filter(s=>!s.hit&&s.x<800);for(const e of enemies){if(e.x<128){e.dead=true;hearts--;message.textContent='A shadow reached the bed!';}}enemies=enemies.filter(e=>!e.dead);if(hearts<=0)return finish(false);if(spawned===waveSize()&&!enemies.length){if(wave===5)return finish(true);wave++;spawned=defeated=0;waveDelay=2600;spawnAt=now+waveDelay;energy=Math.min(150,energy+35);message.textContent=`Wave ${wave} is stirring…`; }update();draw();raf=requestAnimationFrame(loop);}
  function finish(win){running=false;cancelAnimationFrame(raf);best=Math.max(best,wave);localStorage.setItem('playground:night-wave',best);overlay.classList.remove('hidden');overlay.querySelector('p').textContent=win?'Sunrise':'The room went dark';overlay.querySelector('strong').textContent=win?'You saved the dream!':`You reached wave ${wave}`;overlay.querySelector('span').textContent=win?'Every shadow is asleep again.':`Best wave: ${best}. Rearrange your defenders and try again.`;overlay.querySelector('button').textContent=win?'Play another night':'Try the shift again';}
  function draw(){ctx.fillStyle='#28223c';ctx.fillRect(0,0,800,540);ctx.fillStyle='#352d4b';for(let i=0;i<3;i++){ctx.fillRect(128,60+i*150,642,120);ctx.strokeStyle='#5b4f72';ctx.strokeRect(128,60+i*150,642,120);}/* A top-down bed at the end of every dream lane. */ctx.fillStyle='#785448';ctx.beginPath();ctx.roundRect(10,54,120,432,14);ctx.fill();ctx.fillStyle='#b98a6f';ctx.fillRect(14,62,112,18);ctx.fillRect(14,458,112,18);ctx.fillStyle='#f7ead7';ctx.beginPath();ctx.roundRect(23,74,94,392,9);ctx.fill();ctx.fillStyle='#fffaf0';ctx.beginPath();ctx.roundRect(33,86,74,62,18);ctx.fill();ctx.strokeStyle='#d8c7b4';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#8f79aa';ctx.beginPath();ctx.roundRect(23,158,94,308,6);ctx.fill();ctx.fillStyle='#aa91c4';ctx.fillRect(23,158,94,72);ctx.fillStyle='#73628c';ctx.fillRect(23,302,94,72);ctx.strokeStyle='#d9c9eb';ctx.lineWidth=2;ctx.setLineDash([7,6]);for(let y=176;y<454;y+=38){ctx.beginPath();ctx.moveTo(31,y);ctx.lineTo(109,y);ctx.stroke();}ctx.setLineDash([]);ctx.fillStyle='#5d4039';[[15,59],[124,59],[15,476],[124,476]].forEach(([x,y])=>{ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fill();});ctx.fillStyle='#ffe6b0';ctx.beginPath();ctx.arc(70,116,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6f5d82';ctx.beginPath();ctx.arc(75,112,13,0,Math.PI*2);ctx.fill();defenders.forEach(d=>{const info=NIGHT_DEFENDERS[d.kind];ctx.fillStyle=info.color;ctx.beginPath();ctx.roundRect(d.x-24,87+d.lane*150,48,66,10);ctx.fill();ctx.fillStyle='#292238';ctx.textAlign='center';ctx.font='bold 18px DM Sans';ctx.fillText(d.kind==='lamp'?'☀':d.kind==='toy'?'♪':'▤',d.x,127+d.lane*150);});enemies.forEach(e=>{ctx.fillStyle=e.max===8?'#9172ad':'#675879';ctx.beginPath();ctx.arc(e.x,120+e.lane*150,26,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f5d3e8';ctx.fillRect(e.x-8,114+e.lane*150,5,5);ctx.fillRect(e.x+6,114+e.lane*150,5,5);ctx.fillStyle='#191427';ctx.fillRect(e.x-20,151+e.lane*150,40,5);ctx.fillStyle='#e56f87';ctx.fillRect(e.x-20,151+e.lane*150,40*(e.hp/e.max),5);});shots.forEach(s=>{ctx.fillStyle=s.color;ctx.beginPath();ctx.arc(s.x,120+s.lane*150,7,0,Math.PI*2);ctx.fill();});}
  root.addEventListener('click',event=>{const choice=event.target.closest('[data-defender]');if(choice){selected=choice.dataset.defender;root.querySelectorAll('[data-defender]').forEach(b=>b.classList.toggle('selected',b===choice));}if(event.target.closest('[data-start]'))start();if(event.target.closest('[data-clear]')){selected='remove';message.textContent='Choose an object to remove.';}});canvas.addEventListener('pointerdown',event=>{if(!running)return;const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*800/rect.width,y=(event.clientY-rect.top)*540/rect.height,lane=Math.floor((y-60)/150),col=Math.floor((x-145)/120);if(lane<0||lane>2||col<0||col>4)return;const px=175+col*120,index=defenders.findIndex(d=>d.lane===lane&&Math.abs(d.x-px)<10);if(selected==='remove'){if(index>=0){defenders.splice(index,1);message.textContent='Object returned to the toy box.';}return;}if(index>=0){message.textContent='That rug square is occupied.';return;}const item=NIGHT_DEFENDERS[selected];if(energy<item.cost){message.textContent='Not enough dreamlight yet.';return;}energy-=item.cost;defenders.push({kind:selected,lane,x:px,cool:250});message.textContent=`${item.name} is guarding lane ${lane+1}.`;update();draw();});reset();
  return()=>{running=false;cancelAnimationFrame(raf);};
}
