export const PARCEL_MAP = [
  '############', '#S...#.....A#', '#.##.#.###..#', '#....#...#..#', '###.###..#..#', '#...#....#B.#', '#.#...##....#', '#C....#....D#', '############',
];
export const canWalk = (map,x,y) => Boolean(map[y]?.[x] && map[y][x] !== '#');
export const parcelDistance = (a,b) => Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const JOBS=[{to:'A',name:'Mina',parcel:'Moon cake',rule:'Keep it level',color:'#f0bd62'},{to:'B',name:'Pip',parcel:'Singing seed',rule:'Deliver before it sprouts',color:'#78b99a'},{to:'C',name:'Ora',parcel:'Ghost letter',rule:'Take the quiet streets',color:'#ac8bd4'},{to:'D',name:'Sol',parcel:'Sunset tea',rule:'Final delivery',color:'#ed836f'}];

export function mountParcel(root){
  root.innerHTML=`<div class="feature-game parcel-game"><aside class="feature-copy"><p class="eyebrow">A miniature delivery adventure</p><h2>Parcel Quest</h2><p>Pedal through Button Borough, discover shortcuts, and deliver four peculiar packages before the post bell rings.</p><div class="feature-stats"><span>Delivered<b data-delivered>0 / 4</b></span><span>Time<b data-time>1:30</b></span><span>Stamps<b data-stamps>0</b></span><span>Best<b data-best>—</b></span></div><div class="parcel-ticket"><small>Current delivery</small><strong data-parcel>Moon cake → Mina</strong><span data-rule>Keep it level</span></div><p class="feature-help">Move with arrow keys, WASD, swipe, or the street controls. Find glowing shortcuts for bonus stamps.</p></aside><section class="feature-stage parcel-stage"><div class="parcel-map-wrap"><canvas width="720" height="540" aria-label="Map of Button Borough"></canvas><div class="feature-overlay"><p>Button Borough Post</p><strong>Four parcels are waiting.</strong><span>Every resident has a story. Every shortcut has a secret.</span><button data-start>Start deliveries</button></div></div><p class="feature-message" aria-live="polite">The bicycle is ready outside the post office.</p><div class="map-controls"><button data-move="up">↑</button><button data-move="left">←</button><button data-move="down">↓</button><button data-move="right">→</button></div></section></div>`;
  const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),overlay=root.querySelector('.feature-overlay'),message=root.querySelector('.feature-message');let player={x:1,y:1},job=0,delivered=0,stamps=0,time=90,running=false,timer,shortcuts=new Set(['3,3','8,6','2,7']),best=Number(localStorage.getItem('playground:parcel-best')||0),touch;
  root.querySelector('[data-best]').textContent=best?`${best}s`:'—';
  function reset(){clearInterval(timer);player={x:1,y:1};job=0;delivered=0;stamps=0;time=90;running=false;shortcuts=new Set(['3,3','8,6','2,7']);update();draw();}
  function start(){reset();running=true;overlay.classList.add('hidden');message.textContent='First stop: Mina at the amber house.';timer=setInterval(()=>{time--;update();if(time<=0)finish(false);},1000);}
  function update(){root.querySelector('[data-delivered]').textContent=`${delivered} / ${JOBS.length}`;root.querySelector('[data-time]').textContent=`${Math.floor(time/60)}:${String(time%60).padStart(2,'0')}`;root.querySelector('[data-stamps]').textContent=stamps;const current=JOBS[Math.min(job,JOBS.length-1)];root.querySelector('[data-parcel]').textContent=delivered===JOBS.length?'All parcels delivered':`${current.parcel} → ${current.name}`;root.querySelector('[data-rule]').textContent=delivered===JOBS.length?'Route complete':current.rule;}
  function move(name){if(!running)return;const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[name];if(!d)return;const nx=player.x+d[0],ny=player.y+d[1];if(!canWalk(PARCEL_MAP,nx,ny)){message.textContent='A hedge blocks that street.';return;}player={x:nx,y:ny};const key=`${nx},${ny}`;if(shortcuts.delete(key)){stamps++;time=Math.min(99,time+5);message.textContent='Secret lane! Bonus stamp and +5 seconds.';}const tile=PARCEL_MAP[ny][nx],current=JOBS[job];if(tile===current?.to){delivered++;job++;stamps+=2;message.textContent=`Delivered to ${current.name}! Two stamps earned.`;if(delivered===JOBS.length)return finish(true);}else if(/[A-D]/.test(tile))message.textContent='A friendly doorstep—but not this delivery.';update();draw();}
  function finish(win){running=false;clearInterval(timer);if(win){best=Math.max(best,time);localStorage.setItem('playground:parcel-best',best);}update();root.querySelector('[data-best]').textContent=best?`${best}s`:'—';overlay.classList.remove('hidden');overlay.querySelector('p').textContent=win?'Post bell rung':'Post office closed';overlay.querySelector('strong').textContent=win?`${stamps} stamps collected`:`${delivered} of 4 delivered`;overlay.querySelector('span').textContent=win?`You finished with ${time} seconds left.`:'Learn the streets and try a quicker route.';overlay.querySelector('button').textContent=win?'Ride again':'Retry route';}
  function draw(){const cw=60,ch=60;ctx.fillStyle='#cbe0b5';ctx.fillRect(0,0,720,540);for(let y=0;y<PARCEL_MAP.length;y++)for(let x=0;x<PARCEL_MAP[y].length;x++){const tile=PARCEL_MAP[y][x],px=x*cw,py=y*ch;if(tile==='#'){ctx.fillStyle=(x+y)%2?'#547650':'#63845b';ctx.fillRect(px,py,cw,ch);ctx.fillStyle='#719267';ctx.beginPath();ctx.arc(px+15,py+18,13,0,7);ctx.arc(px+42,py+34,17,0,7);ctx.fill();}else{ctx.fillStyle='#e9d7b6';ctx.fillRect(px,py,cw,ch);ctx.strokeStyle='#d5bd99';ctx.setLineDash([8,10]);ctx.beginPath();ctx.moveTo(px,py+30);ctx.lineTo(px+60,py+30);ctx.stroke();ctx.setLineDash([]);}if(/[A-D]/.test(tile)){const j=JOBS.find(v=>v.to===tile);ctx.fillStyle=j.color;ctx.fillRect(px+9,py+9,42,42);ctx.fillStyle='#fff6e6';ctx.fillRect(px+21,py+27,18,24);ctx.fillStyle='#44394d';ctx.textAlign='center';ctx.font='bold 13px DM Sans';ctx.fillText(tile,px+30,py+23);}if(tile==='S'){ctx.fillStyle='#fff7df';ctx.fillRect(px+7,py+7,46,46);ctx.fillStyle='#d95f68';ctx.fillRect(px+15,py+18,30,6);}}shortcuts.forEach(key=>{const[x,y]=key.split(',').map(Number);ctx.fillStyle='#ffe17a';ctx.beginPath();ctx.arc(x*cw+30,y*ch+30,7,0,7);ctx.fill();});ctx.fillStyle='#315d68';ctx.beginPath();ctx.arc(player.x*cw+30,player.y*ch+28,15,0,7);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(player.x*cw+20,player.y*ch+44,9,0,7);ctx.arc(player.x*cw+42,player.y*ch+44,9,0,7);ctx.stroke();}
  const keys={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'},keyHandler=e=>{if(keys[e.key]){e.preventDefault();move(keys[e.key]);}};addEventListener('keydown',keyHandler);root.addEventListener('click',e=>{if(e.target.closest('[data-start]'))start();const d=e.target.closest('[data-move]')?.dataset.move;if(d)move(d);});canvas.addEventListener('pointerdown',e=>touch={x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;if(Math.max(Math.abs(dx),Math.abs(dy))>18)move(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');touch=null;});reset();return()=>{clearInterval(timer);removeEventListener('keydown',keyHandler);};
}
