export const platformLanding = (player, platform, previousBottom) => player.vy >= 0 && previousBottom <= platform.y && player.y + player.h >= platform.y && player.x + player.w > platform.x && player.x < platform.x + platform.w;
export const PATCH_LEVELS=[
  {name:'Button Meadow',sky:'#f5c9b8',start:[35,420],exit:[720,120],platforms:[[0,500,800,40],[110,420,150,22],[315,350,125,22],[500,280,120,22],[660,200,115,22]],patches:[[170,380],[365,310],[550,240]]},
  {name:'Ribbon Ravine',sky:'#b7dacf',start:[30,420],exit:[720,80],platforms:[[0,500,170,40],[220,445,110,20],[390,380,100,20],[540,305,100,20],[670,220,110,20],[570,140,90,18],[700,130,100,20]],patches:[[260,405],[430,340],[610,100]]},
  {name:'Thimble Tower',sky:'#cbbbe3',start:[35,420],exit:[700,55],platforms:[[0,500,150,40],[190,430,90,20],[330,360,90,20],[470,285,90,20],[610,210,90,20],[475,130,90,20],[640,115,140,20]],patches:[[225,390],[505,245],[510,90]],pads:[[350,350],[630,200]]},
];

export function mountPatchwork(root){
  root.innerHTML=`<div class="feature-game patch-game"><aside class="feature-copy"><p class="eyebrow">A handmade platform adventure</p><h2>Patchwork Odyssey</h2><p>Cross a world stitched from fabric and thread. Gather lost patches and reach the spool gate in each tiny chapter.</p><div class="feature-stats"><span>Chapter<b data-level>1 / 3</b></span><span>Patches<b data-patches>0 / 3</b></span><span>Falls<b data-falls>0</b></span><span>Cleared<b data-cleared>0</b></span></div><div class="ability-card"><small>Travel ability</small><strong data-ability>Thread jump</strong><span data-ability-copy>Jump with Space, W, or ↑.</span></div><p class="feature-help">Move with A/D or ←/→. Later chapters unlock gliding and springy button pads.</p></aside><section class="feature-stage patch-stage"><div class="chapter-label"><span data-chapter>Button Meadow</span><b data-patch-message>Three patches are hidden here.</b></div><div class="patch-canvas-wrap"><canvas width="800" height="540" aria-label="Patchwork platforming world"></canvas><div class="feature-overlay"><p>Patchwork Odyssey</p><strong>A seam has come undone.</strong><span>Collect the missing patches and stitch the world back together.</span><button data-start>Begin the journey</button></div></div><div class="platform-controls"><button data-left aria-label="Move left">←</button><button data-jump aria-label="Jump">Jump</button><button data-right aria-label="Move right">→</button></div><p class="feature-message" aria-live="polite">The meadow is waiting.</p></section></div>`;
  const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),overlay=root.querySelector('.feature-overlay'),message=root.querySelector('.feature-message');let levelIndex=0,player,keys={left:false,right:false,jump:false},collected,falls=0,cleared=Number(localStorage.getItem('playground:patch-cleared')||0),running=false,last=0,raf;
  function resetPlayer(){const l=PATCH_LEVELS[levelIndex];player={x:l.start[0],y:l.start[1],w:28,h:42,vx:0,vy:0,grounded:false};}
  function load(index){levelIndex=index;collected=new Set();resetPlayer();update();draw();}
  function start(){falls=0;load(0);running=true;last=performance.now();overlay.classList.add('hidden');message.textContent='Find all three patches, then reach the spool gate.';raf=requestAnimationFrame(loop);}
  function update(){const l=PATCH_LEVELS[levelIndex];root.querySelector('[data-level]').textContent=`${levelIndex+1} / ${PATCH_LEVELS.length}`;root.querySelector('[data-patches]').textContent=`${collected.size} / ${l.patches.length}`;root.querySelector('[data-falls]').textContent=falls;root.querySelector('[data-cleared]').textContent=cleared;root.querySelector('[data-chapter]').textContent=l.name;root.querySelector('[data-patch-message]').textContent=collected.size===l.patches.length?'The spool gate is open!':`${l.patches.length-collected.size} patches remain.`;root.querySelector('[data-ability]').textContent=levelIndex===0?'Thread jump':levelIndex===1?'Ribbon glide':'Button bounce';root.querySelector('[data-ability-copy]').textContent=levelIndex===0?'Jump with Space, W, or ↑.':levelIndex===1?'Hold jump while falling to glide.':'Golden pads launch you extra high.';}
  function loop(now){if(!running)return;const dt=Math.min(.033,(now-last)/1000);last=now;const previousBottom=player.y+player.h;player.vx+=(keys.right-keys.left)*900*dt;player.vx*=.82;player.vx=Math.max(-210,Math.min(210,player.vx));if(keys.jump&&player.grounded){player.vy=-430;player.grounded=false;}let gravity=1050;if(levelIndex===1&&keys.jump&&player.vy>0)gravity=300;player.vy+=gravity*dt;player.x+=player.vx*dt;player.y+=player.vy*dt;player.x=Math.max(0,Math.min(800-player.w,player.x));player.grounded=false;const l=PATCH_LEVELS[levelIndex];for(const p of l.platforms){const platform={x:p[0],y:p[1],w:p[2],h:p[3]};if(platformLanding(player,platform,previousBottom)){player.y=platform.y-player.h;player.vy=0;player.grounded=true;}}for(const p of l.pads||[]){if(Math.abs(player.x+player.w/2-p[0])<35&&player.y+player.h>=p[1]-5&&player.y+player.h<=p[1]+20&&player.vy>=0){player.vy=-610;message.textContent='Boing! The button flings you upward.';}}l.patches.forEach((p,i)=>{if(!collected.has(i)&&Math.hypot(player.x+14-p[0],player.y+20-p[1])<35){collected.add(i);message.textContent='A lost fabric patch!';update();}});const exit=l.exit;if(collected.size===l.patches.length&&Math.hypot(player.x-exit[0],player.y-exit[1])<55){if(levelIndex<PATCH_LEVELS.length-1){levelIndex++;load(levelIndex);message.textContent=`Chapter ${levelIndex+1}: ${PATCH_LEVELS[levelIndex].name}`;}else return finish();}if(player.y>570){falls++;resetPlayer();message.textContent='The thread pulled you safely back.';update();}draw();raf=requestAnimationFrame(loop);}
  function finish(){running=false;cancelAnimationFrame(raf);cleared=Math.max(cleared,3);localStorage.setItem('playground:patch-cleared',cleared);update();overlay.classList.remove('hidden');overlay.querySelector('p').textContent='World repaired';overlay.querySelector('strong').textContent='Every seam is singing.';overlay.querySelector('span').textContent=`Nine patches found with ${falls} ${falls===1?'fall':'falls'}.`;overlay.querySelector('button').textContent='Journey again';}
  function draw(){const l=PATCH_LEVELS[levelIndex];ctx.fillStyle=l.sky;ctx.fillRect(0,0,800,540);ctx.fillStyle='#ffffff33';for(let i=0;i<9;i++){ctx.beginPath();ctx.arc(i*103+30,60+(i%3)*45,22,0,7);ctx.fill();}ctx.strokeStyle='#ffffff55';ctx.setLineDash([5,7]);for(let y=30;y<540;y+=55){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(800,y);ctx.stroke();}ctx.setLineDash([]);l.platforms.forEach((p,i)=>{ctx.fillStyle=i%2?'#6e8d6b':'#58785d';ctx.beginPath();ctx.roundRect(...p,8);ctx.fill();ctx.strokeStyle='#f2e2c8';ctx.lineWidth=3;ctx.setLineDash([7,6]);ctx.stroke();ctx.setLineDash([]);});(l.pads||[]).forEach(p=>{ctx.fillStyle='#f0bf4f';ctx.beginPath();ctx.ellipse(p[0],p[1],30,8,0,0,7);ctx.fill();});l.patches.forEach((p,i)=>{if(collected.has(i))return;ctx.save();ctx.translate(p[0],p[1]);ctx.rotate(.15);ctx.fillStyle=['#e96771','#f2c058','#6ab7a0'][i%3];ctx.fillRect(-12,-12,24,24);ctx.strokeStyle='#fff7df';ctx.setLineDash([3,3]);ctx.strokeRect(-9,-9,18,18);ctx.restore();});ctx.fillStyle=collected.size===l.patches.length?'#ffd166':'#786d7f';ctx.fillRect(l.exit[0],l.exit[1],42,64);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(l.exit[0]+21,l.exit[1]+32,11,0,7);ctx.fill();ctx.fillStyle='#433650';ctx.fillRect(player.x,player.y,player.w,player.h);ctx.fillStyle='#fff0d6';ctx.beginPath();ctx.arc(player.x+14,player.y+10,9,0,7);ctx.fill();ctx.fillStyle='#e85f68';ctx.fillRect(player.x+4,player.y+27,20,5);}
  const map={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'jump',w:'jump',W:'jump',' ':'jump'},down=e=>{if(map[e.key]){e.preventDefault();keys[map[e.key]]=true;}},up=e=>{if(map[e.key])keys[map[e.key]]=false;};addEventListener('keydown',down);addEventListener('keyup',up);root.addEventListener('click',e=>{if(e.target.closest('[data-start]'))start();});[['[data-left]','left'],['[data-right]','right'],['[data-jump]','jump']].forEach(([sel,key])=>{const b=root.querySelector(sel);b.addEventListener('pointerdown',e=>{e.preventDefault();keys[key]=true;});b.addEventListener('pointerup',()=>keys[key]=false);b.addEventListener('pointerleave',()=>keys[key]=false);});load(0);return()=>{running=false;cancelAnimationFrame(raf);removeEventListener('keydown',down);removeEventListener('keyup',up);};
}
