export const flightStep = (state, input, dt) => ({ ...state, vy: Math.max(-240,Math.min(260,state.vy + (input*420 + 85)*dt)), y: state.y + state.vy*dt, distance: state.distance + state.speed*dt });
export const ringCollected = (plane, ring, scroll) => Math.hypot(plane.x-(ring.x-scroll),plane.y-ring.y)<38;
const FLIGHTS=[
  {name:'Bedroom Breeze',sky:['#f6c8aa','#f8e2bd'],length:2100,rings:[[420,210],[720,330],[1040,170],[1390,280],[1730,190]],gusts:[[900,80,180,100]],landing:280},
  {name:'Garden Updraft',sky:['#a6d9d2','#dcedbe'],length:2500,rings:[[380,320],[690,180],[980,120],[1320,310],[1680,160],[2050,250]],gusts:[[780,310,210,100],[1510,60,190,110]],landing:210},
  {name:'Thunder Post',sky:['#566585','#d08c8a'],length:2900,rings:[[430,150],[760,300],[1120,210],[1460,110],[1810,330],[2200,180],[2550,260]],gusts:[[850,60,170,150],[1570,280,210,110],[2320,70,180,120]],landing:260},
];

export function mountSkies(root){
  root.innerHTML=`<div class="feature-game skies-game"><aside class="feature-copy"><p class="eyebrow">A paper-flight adventure</p><h2>Paper Skies</h2><p>Carry lost postcards through bedrooms, gardens, and thunderclouds. Dive for speed, climb on warm air, and land softly.</p><div class="feature-stats"><span>Flight<b data-flight>1 / 3</b></span><span>Stamps<b data-rings>0 / 5</b></span><span>Altitude<b data-altitude>50%</b></span><span>Best<b data-best>0</b></span></div><div class="plane-picker"><small>Paper plane</small><button class="selected" data-plane="dart">Dart</button><button data-plane="glider">Glider</button></div><p class="feature-help">Hold ↑ to climb and ↓ to dive. Release the controls to glide. Fly through stamp rings and touch down in the landing ribbon.</p></aside><section class="feature-stage skies-stage"><div class="flight-banner"><span data-flight-name>Bedroom Breeze</span><b data-flight-message>Postcard secured.</b></div><div class="skies-canvas-wrap"><canvas width="900" height="520" aria-label="Paper airplane flight course"></canvas><div class="feature-overlay"><p>Paper Skies</p><strong>The mail rides the wind.</strong><span>Three flights. Hidden stamp rings. One perfect landing.</span><button data-start>Launch the first postcard</button></div></div><div class="flight-controls"><button data-fly="up">Climb ↑</button><button data-fly="down">Dive ↓</button></div><p class="feature-message" aria-live="polite">Folded, stamped, and ready.</p></section></div>`;
  const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),overlay=root.querySelector('.feature-overlay'),message=root.querySelector('.feature-message');let level=0,state,input=0,rings=new Set(),running=false,last=0,raf,plane='dart',best=Number(localStorage.getItem('playground:skies-best')||0);
  root.querySelector('[data-best]').textContent=best;
  function resetFlight(){state={x:180,y:260,vy:0,distance:0,speed:plane==='dart'?175:150,health:3};rings=new Set();update();draw();}
  function start(){level=0;resetFlight();running=true;last=performance.now();overlay.classList.add('hidden');message.textContent='Catch the first breeze.';raf=requestAnimationFrame(loop);}
  function update(){const f=FLIGHTS[level];root.querySelector('[data-flight]').textContent=`${level+1} / ${FLIGHTS.length}`;root.querySelector('[data-rings]').textContent=`${rings.size} / ${f.rings.length}`;root.querySelector('[data-altitude]').textContent=`${Math.round((1-state.y/520)*100)}%`;root.querySelector('[data-flight-name]').textContent=f.name;root.querySelector('[data-flight-message]').textContent=state.health===3?'Postcard secured.':`${state.health} folds remaining.`;}
  function loop(now){if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;const lift=input*(plane==='glider'?330:420);state=flightStep(state,lift/420,dt);const f=FLIGHTS[level];f.rings.forEach((r,i)=>{if(!rings.has(i)&&ringCollected(state,{x:r[0],y:r[1]},state.distance)){rings.add(i);state.speed+=4;message.textContent='Stamp ring collected!';}});for(const g of f.gusts){const sx=g[0]-state.distance;if(sx>-40&&sx<state.x+20&&state.x<sx+g[2]&&state.y>g[1]&&state.y<g[1]+g[3]){state.vy-=120*dt;message.textContent='An updraft lifts the plane.';}}if(state.y<18||state.y>500){state.health--;state.y=Math.max(30,Math.min(485,state.y));state.vy*=-.35;message.textContent='The postcard crumpled at the edge!';if(state.health<=0)return crash();}if(state.distance>=f.length){const safe=Math.abs(state.y-f.landing)<75&&Math.abs(state.vy)<190;if(!safe)return crash('The landing was too rough.');if(level<FLIGHTS.length-1){level++;resetFlight();message.textContent=`Postcard delivered! Next: ${FLIGHTS[level].name}.`;last=now;}else return finish();}update();draw();raf=requestAnimationFrame(loop);}
  function crash(copy='The wind carried the plane away.'){running=false;cancelAnimationFrame(raf);overlay.classList.remove('hidden');overlay.querySelector('p').textContent='Postcard returned';overlay.querySelector('strong').textContent='Refold and relaunch.';overlay.querySelector('span').textContent=copy;overlay.querySelector('button').textContent='Try all flights again';}
  function finish(){running=false;cancelAnimationFrame(raf);const total=FLIGHTS.reduce((n,f)=>n+f.rings.length,0),earned=Math.min(total,rings.size);best=Math.max(best,earned);localStorage.setItem('playground:skies-best',best);root.querySelector('[data-best]').textContent=best;overlay.classList.remove('hidden');overlay.querySelector('p').textContent='Last postcard delivered';overlay.querySelector('strong').textContent='The paper sky remembers you.';overlay.querySelector('span').textContent=`Final flight stamps: ${rings.size}. Best: ${best}.`;overlay.querySelector('button').textContent='Fly the route again';}
  function draw(){const f=FLIGHTS[level],gradient=ctx.createLinearGradient(0,0,0,520);gradient.addColorStop(0,f.sky[0]);gradient.addColorStop(1,f.sky[1]);ctx.fillStyle=gradient;ctx.fillRect(0,0,900,520);const scroll=state.distance;ctx.fillStyle='#ffffff77';for(let i=0;i<7;i++){const x=((i*230-scroll*.35)%1200+1200)%1200-100,y=70+(i%3)*110;ctx.beginPath();ctx.ellipse(x,y,70,25,0,0,7);ctx.fill();}f.gusts.forEach(g=>{const x=g[0]-scroll;if(x<-g[2]||x>900)return;ctx.fillStyle='#ffffff28';ctx.fillRect(x,g[1],g[2],g[3]);ctx.strokeStyle='#ffffff99';ctx.setLineDash([10,12]);for(let y=g[1]+20;y<g[1]+g[3];y+=30){ctx.beginPath();ctx.moveTo(x+15,y);ctx.lineTo(x+g[2]-15,y);ctx.stroke();}ctx.setLineDash([]);});f.rings.forEach((r,i)=>{if(rings.has(i))return;const x=r[0]-scroll;if(x<-50||x>950)return;ctx.strokeStyle='#f3bd45';ctx.lineWidth=10;ctx.beginPath();ctx.arc(x,r[1],28,0,7);ctx.stroke();ctx.fillStyle='#fff3b2';ctx.font='16px DM Sans';ctx.textAlign='center';ctx.fillText('✦',x,r[1]+6);});const landingX=f.length-scroll;if(landingX<1000&&landingX>-200){ctx.fillStyle='#f8efcf';ctx.fillRect(landingX,f.landing-35,190,70);ctx.strokeStyle='#d85f6e';ctx.lineWidth=5;ctx.strokeRect(landingX,f.landing-35,190,70);ctx.fillStyle='#513c55';ctx.font='bold 16px DM Sans';ctx.fillText('POST LANDING',landingX+95,f.landing+6);}ctx.save();ctx.translate(state.x,state.y);ctx.rotate(Math.atan2(state.vy,state.speed)*.45);ctx.fillStyle=plane==='dart'?'#fff8e9':'#f4e2c2';ctx.strokeStyle='#463950';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(30,0);ctx.lineTo(-28,-17);ctx.lineTo(-12,0);ctx.lineTo(-28,17);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(30,0);ctx.lineTo(-12,0);ctx.stroke();ctx.fillStyle='#d85f6e';ctx.fillRect(-7,-4,12,8);ctx.restore();ctx.fillStyle='#433b54';ctx.fillRect(0,0,Math.max(0,Math.min(900,state.distance/f.length*900)),5);}
  const keyDown=e=>{if(['ArrowUp','w','W'].includes(e.key)){e.preventDefault();input=-1;}if(['ArrowDown','s','S'].includes(e.key)){e.preventDefault();input=1;}},keyUp=e=>{if(['ArrowUp','w','W','ArrowDown','s','S'].includes(e.key))input=0;};addEventListener('keydown',keyDown);addEventListener('keyup',keyUp);root.addEventListener('click',e=>{if(e.target.closest('[data-start]'))start();const pick=e.target.closest('[data-plane]');if(pick&&!running){plane=pick.dataset.plane;root.querySelectorAll('[data-plane]').forEach(b=>b.classList.toggle('selected',b===pick));resetFlight();}});root.querySelectorAll('[data-fly]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();input=b.dataset.fly==='up'?-1:1;});b.addEventListener('pointerup',()=>input=0);b.addEventListener('pointerleave',()=>input=0);});resetFlight();return()=>{running=false;cancelAnimationFrame(raf);removeEventListener('keydown',keyDown);removeEventListener('keyup',keyUp);};
}
