export const DIRECTIONS = { up: { x: 0, y: -1 }, down: { x: 0, y: 1 }, left: { x: -1, y: 0 }, right: { x: 1, y: 0 } };
export const oppositeDirection = (a, b) => a.x + b.x === 0 && a.y + b.y === 0;
export const nextHead = (head, direction, size, wrap = false) => ({
  x: wrap ? (head.x + direction.x + size) % size : head.x + direction.x,
  y: wrap ? (head.y + direction.y + size) % size : head.y + direction.y,
});
export const occupies = (point, points) => points.some(item => item.x === point.x && item.y === point.y);
export const snakeCollision = (head, body, hazards, size, wrap = false) => (!wrap && (head.x < 0 || head.y < 0 || head.x >= size || head.y >= size)) || occupies(head, body) || occupies(head, hazards);
export const fruitReward = (kind, combo = 1) => ({ berry: 10, golden: 30, mushroom: 5 }[kind] || 10) * Math.max(1, combo);

const THEMES = [
  { id: 'garden', name: 'Garden', unlock: 0, bg: '#dff0c8', grid: '#c7dfad', snake: '#315f43', head: '#183d2a', fruit: '#e85964' },
  { id: 'dusk', name: 'Dusk', unlock: 100, bg: '#453b62', grid: '#51486c', snake: '#f6c863', head: '#fff0b0', fruit: '#ef7187' },
  { id: 'pond', name: 'Moon Pond', unlock: 250, bg: '#173d4d', grid: '#214c5d', snake: '#75d8bd', head: '#d7fff3', fruit: '#ff9675' },
];

export function mountSnake(root, settings = {}) {
  root.innerHTML = `<div class="snake-app toy"><aside class="snake-copy"><p class="eyebrow">An arcade garden</p><h2>Garden<br>Serpent</h2><p>Gather fruit, build quick combos, and weave around a garden that grows wilder with you.</p><div class="snake-stats"><span>Score<b data-score>0</b></span><span>Best<b data-best>0</b></span><span>Length<b data-length>3</b></span><span>Combo<b data-combo>×1</b></span></div><label class="snake-field">Mode<select data-mode><option value="adventure">Adventure</option><option value="classic">Classic</option></select></label><label class="snake-field">Garden<select data-theme></select></label><div class="snake-options"><button type="button" data-sound aria-pressed="true">Sound: On</button><button type="button" data-pause disabled>Pause</button></div><p class="snake-legend"><i class="berry-dot"></i> Berry · <i class="gold-dot"></i> Golden · <i class="mushroom-dot"></i> Mushroom</p></aside><section class="snake-stage"><div class="snake-objective"><span>Garden task</span><b data-objective>Collect 3 berries</b><i><em data-progress></em></i></div><div class="snake-board-wrap"><canvas width="600" height="600" aria-label="Garden Serpent game board"></canvas><div class="snake-overlay"><p>Garden Serpent</p><strong>Ready to grow?</strong><span>Use arrow keys, WASD, swipe, or the controls.</span><button type="button" data-start>Start adventure</button></div><div class="weather" aria-live="polite"></div></div><p class="snake-message" aria-live="polite">Choose a mode and begin.</p><div class="snake-controls" aria-label="Direction controls"><button data-direction="up" aria-label="Move up">↑</button><button data-direction="left" aria-label="Move left">←</button><button data-direction="down" aria-label="Move down">↓</button><button data-direction="right" aria-label="Move right">→</button></div></section></div>`;
  const canvas = root.querySelector('canvas'), ctx = canvas.getContext('2d'), SIZE = 20, CELL = canvas.width / SIZE;
  const scoreEl = root.querySelector('[data-score]'), bestEl = root.querySelector('[data-best]'), lengthEl = root.querySelector('[data-length]'), comboEl = root.querySelector('[data-combo]'), message = root.querySelector('.snake-message'), overlay = root.querySelector('.snake-overlay'), weather = root.querySelector('.weather'), pauseButton = root.querySelector('[data-pause]'), modeSelect = root.querySelector('[data-mode]'), themeSelect = root.querySelector('[data-theme]');
  let best = Number(localStorage.getItem('playground:snake-best') || 0), longest = Number(localStorage.getItem('playground:snake-longest') || 3);
  let snake, direction, queued, fruit, hazards, score, combo, lastFruitAt, berries, objective, running = false, paused = false, tickTimer, goldenTimer, rainTimer, calmUntil = 0, rainUntil = 0, audio, sound = true, touchStart; const fallbackSounds=new Set();
  const unlockedThemes = () => THEMES.filter(theme => best >= theme.unlock);
  function syncThemes() { const saved=localStorage.getItem('playground:snake-theme')||'garden'; themeSelect.innerHTML=THEMES.map(theme=>`<option value="${theme.id}" ${best<theme.unlock?'disabled':''}>${theme.name}${best<theme.unlock?` · ${theme.unlock} pts`:''}</option>`).join(''); themeSelect.value=unlockedThemes().some(t=>t.id===saved)?saved:'garden'; }
  function theme() { return THEMES.find(item => item.id === themeSelect.value) || THEMES[0]; }
  function randomEmpty() { const open=[]; for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const p={x,y};if(!occupies(p,snake)&&!occupies(p,hazards)&&(!fruit||p.x!==fruit.x||p.y!==fruit.y))open.push(p);} return open[Math.floor(Math.random()*open.length)] || {x:2,y:2}; }
  function newFruit(kind='berry') { fruit={...randomEmpty(),kind}; if(kind==='golden'){clearTimeout(goldenTimer);goldenTimer=setTimeout(()=>{if(fruit?.kind==='golden'){fruit={...randomEmpty(),kind:'berry'};message.textContent='The golden fruit vanished.';draw();}},5000);} }
  function addHazard() { if(hazards.length<18) hazards.push(randomEmpty()); }
  function setObjective() { const choices=[{text:'Collect 3 berries',type:'berries',goal:3},{text:'Reach a 3× combo',type:'combo',goal:3},{text:'Grow to length 10',type:'length',goal:10}]; objective=choices[Math.floor(Math.random()*choices.length)]; objective.start=objective.type==='berries'?berries:0; updateObjective(); }
  function updateObjective() { let value=objective.type==='berries'?berries-objective.start:objective.type==='combo'?combo:snake.length; const done=value>=objective.goal; root.querySelector('[data-objective]').textContent=done?'Task complete!':objective.text; root.querySelector('[data-progress]').style.width=`${Math.min(100,value/objective.goal*100)}%`; if(done){score+=25;message.textContent='Garden task complete! +25';beep(660,.08);setTimeout(()=>{if(running)setObjective();},700);} }
  function reset() { clearTimers(); snake=[{x:10,y:10},{x:9,y:10},{x:8,y:10}];direction=DIRECTIONS.right;queued=direction;hazards=[];score=0;combo=1;lastFruitAt=0;berries=0;calmUntil=0;rainUntil=0;objective=modeSelect.value==='adventure'?{text:'Collect 3 berries',type:'berries',goal:3,start:0}:{text:'Grow to length 10',type:'length',goal:10,start:0};root.querySelector('[data-objective]').textContent=objective.text;root.querySelector('[data-progress]').style.width='0%';newFruit();running=false;paused=false;overlay.classList.remove('hidden');overlay.querySelector('p').textContent='Garden Serpent';overlay.querySelector('strong').textContent='Ready to grow?';overlay.querySelector('span').textContent=modeSelect.value==='adventure'?'Special fruit, garden tasks, and growing hazards.':'Pure Snake: berries, walls, and increasing speed.';overlay.querySelector('[data-start]').textContent=modeSelect.value==='adventure'?'Start adventure':'Start classic';pauseButton.disabled=true;pauseButton.textContent='Pause';message.textContent='Choose a mode and begin.';update();draw(); }
  async function start() { reset();running=true;overlay.classList.add('hidden');pauseButton.disabled=false;message.textContent='The garden is yours.';lastFruitAt=performance.now();if(sound){await unlockAudio();chime([392,523,659]);}schedule();if(modeSelect.value==='adventure')scheduleRain(); }
  function schedule() { clearTimeout(tickTimer); const now=performance.now(),effect=now < calmUntil ? 1.35 : (now < rainUntil ? 0.75 : 1); if(running&&!paused)tickTimer=setTimeout(step,Math.max(72,155-score*.45)*effect); }
  function step() { direction=queued;const head=nextHead(snake[0],direction,SIZE,false);if(snakeCollision(head,snake.slice(0,-1),hazards,SIZE)){finish();return;}snake.unshift(head);const ate=fruit&&head.x===fruit.x&&head.y===fruit.y;if(ate){const now=performance.now();combo=now-lastFruitAt<4200?Math.min(5,combo+1):1;lastFruitAt=now;score+=fruitReward(fruit.kind,combo);if(fruit.kind==='berry')berries++;if(fruit.kind==='mushroom'){calmUntil=now+5000;message.textContent='Mushroom calm: the garden slows down.';score=Math.max(0,score-2);}else message.textContent=fruit.kind==='golden'?`Golden harvest! ×${combo}`:`Juicy combo ×${combo}`;beep(fruit.kind==='golden'?780:520,.06);if(modeSelect.value==='adventure'&&fruit.kind==='berry'&&berries%4===0)addHazard();newFruit(modeSelect.value==='adventure'&&Math.random()<.18?'golden':modeSelect.value==='adventure'&&Math.random()<.13?'mushroom':'berry');updateObjective();}else{snake.pop();if(performance.now()-lastFruitAt>5000)combo=1;}update();draw();schedule(); }
  function finish() { running=false;clearTimers();best=Math.max(best,score);longest=Math.max(longest,snake.length);localStorage.setItem('playground:snake-best',best);localStorage.setItem('playground:snake-longest',longest);syncThemes();update();pauseButton.disabled=true;overlay.classList.remove('hidden');overlay.querySelector('p').textContent='Garden resting';overlay.querySelector('strong').textContent=`${score} points · length ${snake.length}`;overlay.querySelector('span').textContent=`Best ${best} · longest ${longest}`;overlay.querySelector('[data-start]').textContent='Grow again';message.textContent='The serpent curled up for a rest.';beep(180,.18); }
  function turn(name) { const next=DIRECTIONS[name];if(!next||!running||paused||oppositeDirection(direction,next))return;queued=next; }
  function togglePause() { if(!running)return;paused=!paused;pauseButton.textContent=paused?'Resume':'Pause';message.textContent=paused?'Garden paused.':'Back to growing.';if(paused)clearTimeout(tickTimer);else schedule();draw(); }
  function scheduleRain(){clearTimeout(rainTimer);rainTimer=setTimeout(()=>{if(!running)return;rainUntil=performance.now()+3500;weather.textContent='Rain shower · slippery speed!';weather.classList.add('show');message.textContent='Rain makes the serpent hurry.';chime([330,294,262]);setTimeout(()=>weather.classList.remove('show'),3500);scheduleRain();},10000+Math.random()*8000);}
  function clearTimers(){clearTimeout(tickTimer);clearTimeout(goldenTimer);clearTimeout(rainTimer);}
  async function unlockAudio(){if(!sound)return false;try{const AudioEngine=window.AudioContext||window.webkitAudioContext;if(!AudioEngine)return typeof window.Audio==='function';audio ||= new AudioEngine();if(audio.state==='suspended')await audio.resume();return audio.state==='running';}catch{return typeof window.Audio==='function';}}
  function fallbackTone(frequency,duration,delay){if(typeof window.Audio!=='function')return;setTimeout(()=>{if(!sound)return;const rate=8000,length=Math.floor(rate*duration),buffer=new ArrayBuffer(44+length*2),view=new DataView(buffer),write=(offset,text)=>[...text].forEach((char,index)=>view.setUint8(offset+index,char.charCodeAt(0)));write(0,'RIFF');view.setUint32(4,36+length*2,true);write(8,'WAVEfmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,rate,true);view.setUint32(28,rate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,length*2,true);for(let i=0;i<length;i++){const envelope=Math.min(1,i/70)*(1-i/length);view.setInt16(44+i*2,Math.sin(2*Math.PI*frequency*i/rate)*envelope*6500,true);}let binary='';const bytes=new Uint8Array(buffer);for(let i=0;i<bytes.length;i+=4096)binary+=String.fromCharCode(...bytes.subarray(i,i+4096));const soundFile=new window.Audio(`data:audio/wav;base64,${btoa(binary)}`);fallbackSounds.add(soundFile);soundFile.addEventListener('ended',()=>fallbackSounds.delete(soundFile),{once:true});soundFile.play().catch(()=>fallbackSounds.delete(soundFile));},delay*1000);}
  function beep(frequency,duration=.08,delay=0){if(!sound)return;if(!audio||audio.state!=='running'){fallbackTone(frequency,duration,delay);return;}try{const start=audio.currentTime+delay,osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(frequency,start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(.075,start+.012);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(gain).connect(audio.destination);osc.start(start);osc.stop(start+duration+.02);}catch{fallbackTone(frequency,duration,delay);}}
  function chime(notes){notes.forEach((note,index)=>beep(note,.11,index*.085));}
  function update(){scoreEl.textContent=score;bestEl.textContent=best;lengthEl.textContent=snake.length;comboEl.textContent=`×${combo}`;}
  function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
  function draw(){const t=theme();ctx.fillStyle=t.bg;ctx.fillRect(0,0,600,600);ctx.strokeStyle=t.grid;ctx.lineWidth=1;for(let i=0;i<=SIZE;i++){ctx.beginPath();ctx.moveTo(i*CELL,0);ctx.lineTo(i*CELL,600);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*CELL);ctx.lineTo(600,i*CELL);ctx.stroke();}hazards.forEach((p,i)=>{ctx.fillStyle=i%2?'#5b674c':'#6f7558';rounded(p.x*CELL+4,p.y*CELL+5,CELL-8,CELL-9,7);ctx.strokeStyle='#424d39';ctx.lineWidth=2;ctx.stroke();});if(fruit){const cx=fruit.x*CELL+CELL/2,cy=fruit.y*CELL+CELL/2;ctx.fillStyle=fruit.kind==='golden'?'#ffd34e':fruit.kind==='mushroom'?'#b68ad5':t.fruit;ctx.beginPath();ctx.arc(cx,cy,CELL*.32,0,Math.PI*2);ctx.fill();ctx.fillStyle='#315f43';ctx.fillRect(cx-1,cy-CELL*.45,3,7);if(fruit.kind==='golden'&&!settings.reducedMotion){ctx.strokeStyle='#fff3a6';ctx.lineWidth=3;ctx.beginPath();ctx.arc(cx,cy,CELL*.43,0,Math.PI*2);ctx.stroke();}}snake.slice().reverse().forEach((p,index,reverse)=>{const isHead=reverse===snake.length-1;ctx.fillStyle=isHead?t.head:t.snake;rounded(p.x*CELL+2,p.y*CELL+2,CELL-4,CELL-4,9);if(isHead){ctx.fillStyle=t.bg;const horizontal=direction.x!==0;const positions=horizontal?[[direction.x>0?20:8,9],[direction.x>0?20:8,19]]:[[9,direction.y>0?20:8],[19,direction.y>0?20:8]];positions.forEach(([x,y])=>{ctx.beginPath();ctx.arc(p.x*CELL+x,p.y*CELL+y,2.6,0,Math.PI*2);ctx.fill();});}});if(paused){ctx.fillStyle='#292238cc';ctx.fillRect(0,0,600,600);ctx.fillStyle='#fffaf4';ctx.textAlign='center';ctx.font="600 48px Fraunces";ctx.fillText('Garden paused',300,300);}}
  const keyHandler=event=>{const keys={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};if(keys[event.key]){event.preventDefault();turn(keys[event.key]);}if(event.key===' '){event.preventDefault();togglePause();}};
  addEventListener('keydown',keyHandler);root.addEventListener('click',async event=>{const dir=event.target.closest('[data-direction]')?.dataset.direction;if(dir)turn(dir);if(event.target.closest('[data-start]'))await start();if(event.target.closest('[data-pause]'))togglePause();if(event.target.closest('[data-sound]')){sound=!sound;const button=root.querySelector('[data-sound]');button.setAttribute('aria-pressed',sound);button.textContent=sound?'Sound: On':'Sound: Off';if(sound){await unlockAudio();chime([440,660]);message.textContent='Sound is on.';}else message.textContent='Sound is off.';}});canvas.addEventListener('pointerdown',event=>{touchStart={x:event.clientX,y:event.clientY};});canvas.addEventListener('pointerup',event=>{if(!touchStart)return;const dx=event.clientX-touchStart.x,dy=event.clientY-touchStart.y;if(Math.max(Math.abs(dx),Math.abs(dy))>18)turn(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');touchStart=null;});modeSelect.addEventListener('change',reset);themeSelect.addEventListener('change',()=>{localStorage.setItem('playground:snake-theme',themeSelect.value);draw();});
  syncThemes();reset();
  return () => { running=false;clearTimers();removeEventListener('keydown',keyHandler);fallbackSounds.forEach(item=>{item.pause();item.src='';});fallbackSounds.clear();if(audio)audio.close(); };
}
